### ISSUE TITLE
Solving blurry pixelart

### ISSUE THREAD

**Issue by Roboe** [Adalab/clarke-fc-pokemon-Tokytome#1]
Sprites are blurry. Noone really likes blurry sprites, so let's fix that.

There's this experimental, next-CSS property called [image-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering).

`create-react-app` uses Autoprefixer in CSS files to handle compatibility between browsers and implementations. `image-rendering: pixelated` with a fallback to `image-rendering: crisp-edges` should be enough to bring those 4-bits beauty from the past, then.

Buuut in this React webapp, inline styles are in use and they don't take advantage of Autoprefixer. It needs to be added manually. This is the output from https://autoprefixer.github.io:

```css
img {
  image-rendering: crisp-edges;
  -ms-interpolation-mode: nearest-neighbor;
  image-rendering: -webkit-optimize-contrast;
  image-rendering: -moz-crisp-edges;
  image-rendering: -o-pixelated;
  image-rendering: pixelated;
}
```
